### PR TITLE
UPD(Ansible) with_dict -> loop ansible 2.9+ requirement

### PR DESCRIPTION
**Pull request by michalxo**
https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.9.html#loops

FYI guys!

### CODE REVIEW

**Review by fgiorgetti — APPROVED** [review]
Looks  good

**Comment by michalxo** [comment]
This does not solve the issue. Seems like there is a regression in ansible 2.9.x.
Or we're hitting similar issue https://github.com/ansible/ansible/issues/64169

**Comment by fgiorgetti** [comment]
@michalxo two things from the issue you mentioned:
1 - did you see this comment:
https://github.com/ansible/ansible/issues/64169#issuecomment-548811653

2 - there is another comment saying to try using ansible from devel branch. At least you can verify if it has been fixed upstream.

**Comment by michalxo** [comment]
I have finally found the real issue. It was in description of service, which was calling `lookup('env', 'MY_VAR')` - once this is removed, all is fine. Interesting bug in ansible 2.9.x.
```
amq_broker_download_url: "{{ lookup('env','AMQ_BROKER_DOWNLOAD_URL') | default('https://archive.apache.org/dist/activemq/activemq-artemis/2.6.2/apache-artemis-2.6.2-bin.zip', true) }}"
...
service_opts:
  "artemis-{{ amq_broker_instance_dir }}":
    After: "syslog.target network.target"
    Description: "{% if 'artemis' in amq_broker_download_url|lower %}Apache ActiveMQ Artemis{% else %}Red Hat AMQ 7{% endif %}"  # BUG! amq_broker_download_url
#   Description: "{% if 'artemis' in amq_broker_instance_home|lower %}Apache ActiveMQ Artemis{% else %}Red Hat AMQ 7{% endif %}"  # works
```

**Comment by michalxo** [comment]
Our solution. @fgiorgetti @enkeys @jdanekrh WDYT guys? Will we allow it by default for us?
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-allow-unsafe-lookups

**Comment by michalxo** [comment]
Need to have these changes in master anyway. Ansible 2.9.4 is not letting me through. Reopening it and merging, because it has been approved previously.

**Pull request merged**
